### ISSUE TITLE
Is there a way to show username?

### ISSUE THREAD

**Issue by kevin7** [Bolandish/Instagram-Grabber#1]
Love your script. At the moment, it's displaying user id for each post. I'm wondering, is it possible to retrieve username based on user id without using API?

**Comment by Bolandish** [comment]
Hi! 
I have added username now :)

**Comment by Bolandish** [comment]
@kevin7 let me know if my fix works :)

**Comment by kevin7** [comment]
Hey Bolandish,

Thanks for the prompt action but it doesn't return username, just id.

**Comment by Bolandish** [comment]
@kevin7 please try fetch my code again..
You can see the response right here
![image](https://cloud.githubusercontent.com/assets/7235443/15891946/43ff7470-2d77-11e6-9174-d60e7e76e52c.png)

**Comment by kevin7** [comment]
Legend, it works perfectly.
