### ISSUE TITLE
How can I get comments in details please

### ISSUE THREAD

**Issue by beli63** [Bolandish/Instagram-Grabber#12]
It's me again :)

I want to get comments in this way :

**comments{
    count,
    nodes {
            id,
            created_at,
            text,
            user {
                 id,
                 profile_pic_url,
                 username
            }
    },
    page_info
}**

Is it possible ?

Thx

**Comment by Bolandish** [comment]
Try again.. I have added a parameter to the functions named **comment_count**..  As standard it is false :)

**Comment by beli63** [comment]
Thx it works.

I just have a last questions, what is the parameter **$assoc** please ?

**Comment by Bolandish** [comment]
Perfekt! 
Assoc is how you want your data return.. Some wants arrays instead of objects :)

**Comment by beli63** [comment]
Okay okay.

So very thank you :)
