### ISSUE TITLE
Error when execute getMediaByHashtag

### ISSUE THREAD

**Issue by holymanz** [Bolandish/Instagram-Grabber#13]
i got this error when try to use getMediaByHashtag function

file_get_contents(https://www.instagram.com/query/?q=ig_hashtag%28snow%29+%7B+media.first%2810%29+%7B+++count%2C+++nodes+%7B+++++caption%2C+++++code%2C++++comments.last%28%29+%7B+++++++++++count%2C+++++++++++nodes+%7B+++++++++++++id%2C+++++++++++++created_at%2C+++++++++++++text%2C+++++++++++++user+%7B+++++++++++++++id%2C+++++++++++++++profile_pic_url%2C+++++++++++++++username+++++++++++++%7D+++++++++++%7D%2C+++++++++++page_info+++++++++%7D%2C+++++date%2C+++++dimensions+%7B+++++++height%2C+++++++width+++++%7D%2C+++++display_src%2C+++++id%2C+++++is_video%2C+++++likes+%7B+++++++count+++++%7D%2C+++++owner+%7B+++++++id%2C+++++++username%2C+++++++full_name%2C+++++++profile_pic_url%2C+++++biography+++++%7D%2C+++++thumbnail_src%2C+++++video_views%2C+++++video_url+++%7D%2C+++page_info+%7D++%7D&ref=tags%3A%3Ashow): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

**Comment by Bolandish** [comment]
Hi @holymanz ! :)
What does you write in the comment_count parameter ?

**Comment by Bolandish** [comment]
@holymanz will you please fetch my new update 1.0.9 :)

**Comment by holymanz** [comment]
Its work..Awesome!!! thank you
