### ISSUE TITLE
how to get small images

### ISSUE THREAD

**Issue by 262media** [Bolandish/Instagram-Grabber#15]
is there a way to get only thumbnails instead of the actual large images?

**Comment by nagualcode** [comment]
$value -> thumbnail_src

**Comment by 262media** [comment]
`echo '<li><a href="'.'https://www.instagram.com/p/'.$media[$key]->code.'" target="_blank"><img src="'.$media[$key]->thumbnail_src.'" alt="'.$media[$key]->caption.'" /></a></li>';
`
still gives the 640px image ...
what am i doing wrong?

**Comment by PelleRavn** [comment]
@262media 640x640 is a thumbnail. If you look at the size of the original pictures, they are a bit more. Most of the images in my stream is 1080x1080

**Comment by 262media** [comment]
ty @PelleRavn
