### ISSUE TITLE
Question: I really need the age of the video, or original date posted

### ISSUE THREAD

**Issue by samdonato** [Bolandish/Instagram-Grabber#16]
First, this is fantastic work.  It works great and it has been a lifesaver.  I have one issue though which is that I need the create date or age of the video. Is it possible?

**Comment by Bolandish** [comment]
Sorry about my late answer.. I will look for a solution within a day :)

**Comment by samdonato** [comment]
It's my issue Bolandish.  Date is sent properly right on the root, I just didn't see it
