### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by geetpurwar** [Bolandish/Instagram-Grabber#2]
Hi,

Its seems to be not working. I used it as follows and it doesn't show images.
Screenshot: http://grab.by/QFIC

Let me know what I am missing.
Thanks.

**Comment by Bolandish** [comment]
Do you get any kind of errors?

**Comment by geetpurwar** [comment]
Its shows me an empty array. What I have done is included the script as you have.
and called of the function as follows: 
<?php print_r(getImagesByHashtag("notUs", 16)); ?>

**Comment by Bolandish** [comment]
@geetpurwar I found the solution.. Try fetch my code again :)

**Comment by geetpurwar** [comment]
Awesome! It worked. Kudos!

**Comment by geetpurwar** [comment]
Hi,

You seems to have make this code complicated.
Can you modify this in form of a snippet, that
we can include in wordpress page.

Let me know what you think.
I am still using your old code, however sometimes that fetch only few images
such as 2 or 3 while I require atleast 6-10.

Thanks.

On Wed, Jun 8, 2016 at 4:51 PM, Thomas Bolander notifications@github.com
wrote:

> I found the solution.. Try fetch my code again :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Bolandish/Instagram-Hashtag-Grabber/issues/2#issuecomment-224560863,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA_Pa0_6G6hJqfLJnMd-yvsn2b3QeM9Mks5qJqW_gaJpZM4Iw2g5
> .

## 

Geet Purwar
http://geetpurwar.com/

[image: Facebook] http://www.facebook.com/geet.design.studio [image:
LinkedIn] http://www.linkedin.com/in/geetpurwar [image: Twitter]
http://twitter.com/geetpurwar

**Comment by Bolandish** [comment]
@geetpurwar Complicated ? The only thing is i added composer to it and maked the functions statics :)

Yeah, i know .. i have tried to figure out the system, but i can't.. 
The api is used on their website to pull medias.. Maybe its because of that :)

**Comment by geetpurwar** [comment]
So technically its the same as old snippet.
Right?

On Monday 13 June 2016, Thomas Bolander notifications@github.com wrote:

> Complicated ? The only thing is i added composer to it and maked the
> functions statics :)
> 
> Yeah, i know .. i have tried to figure out the system, but i can't..
> The api is used on their website to pull medias.. Maybe its because of
> that :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Bolandish/Instagram-Grabber/issues/2#issuecomment-225507107,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA_Pa-4_2UM3iOJpRk4P9qpSP-zNYgrzks5qLQahgaJpZM4Iw2g5
> .

## 

Geet Purwar
http://geetpurwar.com/

[image: Facebook] http://www.facebook.com/geet.design.studio [image:
LinkedIn] http://www.linkedin.com/in/geetpurwar [image: Twitter]
http://twitter.com/geetpurwar

**Comment by Bolandish** [comment]
Exactly.. If you have some edits, let me know :)

**Comment by geetpurwar** [comment]
Not yet. Sometimes script behaves weirdly, however mostly its good.
Thanks for it.

On Mon, Jun 13, 2016 at 1:01 PM, Thomas Bolander notifications@github.com
wrote:

> Exactly.. If you have some edits, let me know :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Bolandish/Instagram-Grabber/issues/2#issuecomment-225507644,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA_Pa0k2OdhR6ZPW9yrUwajJn124NYN4ks5qLQdkgaJpZM4Iw2g5
> .

## 

Geet Purwar
http://geetpurwar.com/

[image: Facebook] http://www.facebook.com/geet.design.studio [image:
LinkedIn] http://www.linkedin.com/in/geetpurwar [image: Twitter]
http://twitter.com/geetpurwar

**Comment by riiino** [comment]
Hi i want to show hashtag content. and not so good at PHP.
i downloaded this, but im not sure which one i need to include. or where to put these code.
so could you tell me how it works more specific please!

**Comment by riiino** [comment]
i ran test.php on my page. i got this error message.
line 14 is
"$media = json_decode(file_get_contents($url), ($assoc || $assoc == "array"));"
can you give me any help with this?

Warning: file_get_contents(https://www.instagram.com/query/?q=ig_hashtag%28nofilter%29+%7B+media.first%2810%29+%7B+++count%2C+++nodes+%7B+++++caption%2C+++++code%2C++++comments.last%28%29+%7B+++++++++++count%2C+++++++++++nodes+%7B+++++++++++++id%2C+++++++++++++created_at%2C+++++++++++++text%2C+++++++++++++user+%7B+++++++++++++++id%2C+++++++++++++++profile_pic_url%2C+++++++++++++++username+++++++++++++%7D+++++++++++%7D%2C+++++++++++page_info+++++++++%7D%2C+++++date%2C+++++dimensions+%7B+++++++height%2C+++++++width+++++%7D%2C+++++display_src%2C+++++id%2C+++++is_video%2C+++++likes+%7B+++++++count+++++%7D%2C+++++owner+%7B+++++++id%2C+++++++username%2C+++++++full_name%2C+++++++profile_pic_url%2C+++++biography+++++%7D%2C+++++thumbnail_src%2C+++++video_views%2C+++++video_url+++%7D%2C+++page_info+%7D++%7D&ref=tags%3A%3Ashow) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 400 BAD REQUEST in /var/www/html/gourmet-event.jp/vendor/Instagram.php on line 14

**Comment by Bolandish** [comment]
Hi @riiino please update to the latest (1.0.9)..
In 1.0.8 a bug was detected :)

**Comment by riiino** [comment]
hi thank you for fast replay!
i tried and it seems to be working, but i only got 32 images. can't get any more...
i want to get as much as hashtag matches.
is this API's problem?

**Comment by Bolandish** [comment]
Yeah.. I dont know how they use the count parameter.. 
I can't see a pattern.. Try write 100 in it :)

**Comment by riiino** [comment]
i tried 100, but still no more 32.
do you get more than 32 images on your page ??

**Comment by Bolandish** [comment]
I haven't tried.. 
I can add a function to get the next 32 images?

**Comment by riiino** [comment]
can you do that? plz
if you dont know how many it can get...its not good.
i really appreciate if you can fix it.
