### ISSUE TITLE
Does not work...

### ISSUE THREAD

**Issue by pixelbart** [Bolandish/Instagram-Grabber#25]
Hello!

I've worked the last day with your class... today it does not working anymore.

Any ideas?

Thanks!

**Comment by hahatey** [comment]
@Bolandish , @Vassardish    me too, not working any more. 

> failed to open stream: HTTP request failed! HTTP/1.1 405 Method Not Allowed
>  in  vendor/bolandish/instagram-grabber/src/Instagram.php  on line  19

or trying with the latest updated Instagram.php  : 

> Notice: Trying to get property of non-object in vendor/bolandish/instagram-grabber/src/Instagram.php on line 36

If now must use access-token to fetch,  please update the repo to provide a config option.

**Comment by paha77** [comment]
It seems like that Instagram has changed the endpoint URL's.  It works with

`https://www.instagram.com/explore/tags/[HASHTAG]/?__a=1`

but I haven't figured it out how to pass the parameters like paging or etc.

**Comment by Bolandish** [comment]
God damn.. I will try looking into the problem . If you found a solution, feel free to make a pull request :)

**Comment by paha77** [comment]
I'm working on it but only besides my daily work.  I've also figured it out that there's a second POST request to 

`https://www.instagram.com/query/`

with the same parameters you use in the current version of the script, the only difference is that it's a POST request.

**Comment by paha77** [comment]
The 

`https://www.instagram.com/explore/tags/[HASHTAG]/?__a=1` request gives us the last 18 posts back.

**Comment by Bolandish** [comment]
We found a solution.. A update will come within an hour :)

**Comment by Bolandish** [comment]
Please update the script :)

**Comment by Bolandish** [comment]
@paha77 @pixelbart  @hahatey

**Comment by hahatey** [comment]
@Bolandish  
Thanks very much,  is now working great . 

$media = json_decode(static::getContentsFromUrl($parameters), ($assoc || $assoc == "array"));

just a little question abt api part, 
is there sth like  **"next_page_url"** returned for "load more" features ?   is using "max_id" 
(query for a big $count number might be heavy and takes longer time to response and render the page.) 


```
stdClass Object
(
    [status] => ok
    [media] => stdClass Object
        (
            [count] => 13354692
            [page_info] => stdClass Object
                (
                    [has_previous_page] => 
                    [start_cursor] => 1391052535586251220
                    [end_cursor] => J0HWDe3RgAAAF0HWDe2XwAAAFiAA
                    [has_next_page] => 1
                )
            [nodes] => Array(
                  ......  .........  ........   
            ) 
)
```

**Comment by Bolandish** [comment]
@hahatey Maybe in the future. Make an issue and we will look into it :)

**Comment by hahatey** [comment]
ok I made it under https://github.com/Bolandish/Instagram-Grabber/issues/19 
and thanks for the great work hope it works better.

**Comment by omarhanandeh** [comment]
i can't get  page_info 'cursor id ...etc' ,how i can do it?
