### ISSUE TITLE
Use arrays instead of stdClass Objects?

### ISSUE THREAD

**Issue by t1maccapp** [Bolandish/Instagram-Grabber#5]

**Comment by Bolandish** [comment]
@t1maccapp why ? :)

**Comment by jstrellner** [comment]
@t1maccapp Just add true to the line with the json_decode;

```
$media = json_decode(file_get_contents($url), true);
```

@Bolandish FYI, I prefer arrays as well.

**Comment by Bolandish** [comment]
@jstrellner @t1maccapp 
Bolandish\Instagram::getMediaByHashtag("nofilter", 10, "array");
