### ISSUE TITLE
How I add max_id parameter on call request ?

### ISSUE THREAD

**Issue by beli63** [Bolandish/Instagram-Grabber#8]
Hello,

First, thanks for your code.
So I'm not php developer and I want to add the max_id parameter to the call request.
How can I do this please ?

Thx man.

**Comment by beli63** [comment]
I test this but return null.
            $parameters = urlencode("ig_user($user) { feed { media.after($max_id, $count) {   count,   nodes {     caption,     code,     comments {       count     },     date,     dimensions {       height,       width     },     display_src,     id,     is_video,     likes {       count     },     owner {       id,       username     },     thumbnail_src,     video_views,     video_url   },   page_info }  }  }");

**Comment by Bolandish** [comment]
Hi @beli63 .

The example you postes is right.. The only thing you need to correct is max_id..
Its not actually the ID of a post you should use. In the response from instagram you can find something called **end_cursor** in a object called **page_info**. That's the id :)
The end_cursor looks like **J0HV1lHUAAAAF0HV1kzuwAAAFiYA**

**Comment by Bolandish** [comment]
@beli63 the code you post. actually works :)

`ig_user(460563723){ media.after(1060728019300790746, 20) {   count,   nodes {     caption,     code,     comments {       count     },     date,     dimensions {       height,       width     },     display_src,     id,     is_video,     likes {       count     },     owner {       id,       username     },     thumbnail_src,     video_views   },   page_info }  }`

**Comment by Bolandish** [comment]
Remove the **Feed** from ur parameter and it will work :)

**Comment by Bolandish** [comment]
@beli63 i will push an update to you :)

**Comment by beli63** [comment]
Thanks, it's perfect :)

**Comment by Bolandish** [comment]
V1.0.1 check it out :)

**Comment by beli63** [comment]
Great !

Thank you very much.
